### ISSUE TITLE
Periodic releases

### ISSUE THREAD

**Issue by nitrocode** [suzuki-shunsuke/tfprovidercheck#352]
Hi @suzuki-shunsuke. Thanks for building this helpful tool.

I noticed that renovate and renovate-approve bots are enabled here. I saw there are recent merges by these bots, however the last release is Nov 2023. 

Could you enable periodic releases using goreleaser and github actions ? Perhaps it can release a new minor version once a month if there are renovatebot merges ?

**Comment by suzuki-shunsuke** [comment]
I checked the update between the latest version v0.2.0 and the main branch.

https://github.com/suzuki-shunsuke/tfprovidercheck/compare/v0.2.0...main

- Update Go 1.21.3 to 1.23.0
- Update Go directive 1.21.3 to 1.22.2
- Update some Go libraries in go.mod
- Update Cosign v1.13.1 to v2.4.0
- Update Goreleaser v1.21.2 to v2.2.0

Do you need any update?

The idea of periodic release is interesting, but I'm not sure if it is good and necessary.

**Comment by suzuki-shunsuke** [comment]
Do you know any project doing periodic releases?

- I know that [Renovate creates releases when the main branch is updated]( https://github.com/renovatebot/renovate/blob/fc0399a89ae04a9ad6aeea8619079996db891713/.github/workflows/build.yml) ([example](https://github.com/renovatebot/renovate/releases/tag/38.52.0)), though this isn't the periodic release

**Comment by nitrocode** [comment]
Thanks for responding quickly. I look at recent releases to ensure if a repository is maintained to integrate it into the CI process. If there hasn't been a release in almost a year then that's usually one less reason to use a tool. While I don't technically need a release to use the tool, the client I work for does require a recent release.

Periodic releases aren't necessary. I do know that goreleaser has this feature under their "nightly builds" docs.

https://goreleaser.com/blog/nightly-actions/#implementing-nightly-builds

Of course, no need to build nightly. Judging by the cadence of renovate PRs merged, it could be released monthly if you're thinking about automating it.

For now, a single manual new release, even a patch, would go a long way.

Thank you for considering

**Comment by suzuki-shunsuke** [comment]
Thank you for your explanation.

> If there hasn't been a release in almost a year then that's usually one less reason to use a tool. While I don't technically need a release to use the tool, the client I work for does require a recent release.

I see. That makes sense.

> For now, a single manual new release, even a patch, would go a long way.

I'll create a release soon.

**Comment by suzuki-shunsuke** [comment]
Released v1.0.0.

https://github.com/suzuki-shunsuke/tfprovidercheck/releases/tag/v1.0.0

I close this issue for now.

**Comment by nitrocode** [comment]
Thank you very much!
